// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - 2014-04-09 13:12:38 -0300
// =======================================================================================
package br.com.splgenerator.model.cadastro;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Funcionario implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;
	
	private String nome;
	private int idade;
	private String cpf;
	private String endereco;
	
	@Column(name = "DATA_NASCIMENTO")
	@Temporal(TemporalType.DATE)
	private Date dataNascimento;
	
	@Column(name = "DATA_ADMISSAO")
	@Temporal(TemporalType.DATE)
	private Date dataAdmissao;
	
	private String email;
	private String banco;
	private int agencia;
	private int conta;
	private String cargo;
	private int salario;
	
	@Column(name = "AFASTAMENTO_INICIO")
	@Temporal(TemporalType.DATE)
	private Date afastamentoInicio;
	
	@Column(name = "AFASTAMENTO_DIAS")
	private int afastamentoDias;
	
	@Column(name = "DATA_DESLIGAMENTO")
	@Temporal(TemporalType.DATE)
	private Date dataDesligamento;
	
	@Column(name = "TIPO_PAGAMENTO")
	private String tipoPagamento;
	
	@Column(name = "BONUS")
	private int bonus;
	
	@Column(name = "REEMBOLSO")
	private int reembolso;

	public Funcionario() {

	}

	public long getId() {
		return id;
	}

	public void setId(long value) {
		id = value;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String value) {
		nome = value;
	}

	public int getIdade() {
		return idade;
	}

	public void setIdade(int value) {
		idade = value;
	}

	public String getCpf() {
		return cpf;
	}

	public void setCpf(String value) {
		cpf = value;
	}

	public String getEndereco() {
		return endereco;
	}

	public void setEndereco(String value) {
		endereco = value;
	}

	public Date getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(Date _dataNascimento) {
		this.dataNascimento = _dataNascimento;
	}

	public Date getDataAdmissao() {
		return dataAdmissao;
	}

	public void setDataAdmissao(Date _dataAdmissao) {
		this.dataAdmissao = _dataAdmissao;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getBanco() {
		return banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	public int getAgencia() {
		return agencia;
	}

	public void setAgencia(int agencia) {
		this.agencia = agencia;
	}

	public int getConta() {
		return conta;
	}

	public void setConta(int conta) {
		this.conta = conta;
	}

	public String getCargo() {
		return cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public int getSalario() {
		return salario;
	}

	public void setSalario(int salario) {
		this.salario = salario;
	}

	public Date getAfastamentoInicio() {
		return afastamentoInicio;
	}

	public void setAfastamentoInicio(Date afastamentoInicio) {
		this.afastamentoInicio = afastamentoInicio;
	}

	public int getAfastamentoDias() {
		return afastamentoDias;
	}

	public void setAfastamentoDias(int afastamentoDias) {
		this.afastamentoDias = afastamentoDias;
	}

	public Date getDataDesligamento() {
		return dataDesligamento;
	}

	public void setDataDesligamento(Date dataDesligamento) {
		this.dataDesligamento = dataDesligamento;
	}

	public String getTipoPagamento() {
		return tipoPagamento;
	}

	public void setTipoPagamento(String tipoPagamento) {
		this.tipoPagamento = tipoPagamento;
	}

	public int getBonus() {
		return bonus;
	}

	public void setBonus(int bonus) {
		this.bonus = bonus;
	}

	public int getReembolso() {
		return reembolso;
	}

	public void setReembolso(int reembolso) {
		this.reembolso = reembolso;
	}

}
