// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - <%= Time.now %>
// =======================================================================================
package br.com.splgenerator.web.servlets.monitoring;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import br.com.splgenerator.web.servlets.monitoring.MonitoringFactory.MonitoringType;

@WebServlet("/monitoring")
public class MonitoringServlet extends HttpServlet {

	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		try {
			IModRhStats stats = MonitoringFactory.getMonitoring(MonitoringType.$VP-MONITORING);
			response.getWriter().println(stats.printStats());
		} catch (Exception e) {
			throw new ServletException(e);
		}
	}
}
