// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - <%= Time.now %>
// =======================================================================================
package <%= managed_bean.package() %>;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.component.html.HtmlDataTable;
import javax.faces.context.FacesContext;

@ManagedBean
@SessionScoped
public class <%= managed_bean.name() %> implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@ManagedProperty(value="#{<%= managed_bean.dao.value() %>}")
	private <%= managed_bean.dao.interface() %> dao;
	
	@ManagedProperty(value="#{<%= managed_bean.log.value() %>}")
	private <%= managed_bean.log.interface() %> log;
	
	private HtmlDataTable htmlDataTable;
	
	<% fields.each { |field| %>
	private <%= field.type() %> _<%= field.name() %>;
	<% } %>
	
	public <%= managed_bean.name() %>() { 
	<% fields.each { |field| %>
		_<%= field.name() %> = <%= field.value() %>;<% } %>
	}
	
	public void setDao(<%= managed_bean.dao.interface() %> dao) {
		this.dao = dao;
	}
	
	public void setLog(<%= managed_bean.log.interface() %> log) {
		this.log = log;
	}
	
	public HtmlDataTable getHtmlDataTable() {
        return htmlDataTable;
    }

    public void setHtmlDataTable(HtmlDataTable htmlDataTable) {
        this.htmlDataTable = htmlDataTable;
    }
	
	<% operations.each { |operation| %>
	public <%= operation.return_type %> <%= operation.name %>() {
		log.log("TRACE", "Executando <%= operation.name %>()...");
	<%= operation.body %>
	}
	<% } %>
	
	<% 
	fields.each { |field| 
	if (field.getter_setter() == true)%>
	public <%= field.type() %> get<%= field.name().capitalize %>() { return _<%= field.name() %>; }
	public void set<%= field.name().capitalize %>( <%= field.type() %> value ) { _<%= field.name() %> = value; }
	<% 
	end
	} 
		%>
	
	private void addFacesMessage(String message) {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(message));
	}

}
