// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - 2014-07-16 00:08:56 -0300
// =======================================================================================
package br.com.splgenerator.web.relatorio;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.component.html.HtmlDataTable;

import br.com.splgenerator.model.cadastro.Funcionario;

@ManagedBean
@RequestScoped
public class RelatorioAniversariantes implements Serializable {

	private static final long serialVersionUID = 1L;

	@ManagedProperty(value="#{$VP-DAO}")
	private br.com.splgenerator.dao.ModRhDao dao;
	@ManagedProperty(value="#{$VP-AUDIT}")
	private br.com.splgenerator.audit.ILog log;

	private HtmlDataTable htmlDataTable;

	private List<Funcionario> funcionarios = new ArrayList<Funcionario>();
	private Date dataAdmissaoDe;
	private Date dataAdmissaoAte;
	private int mesAniversario;
	private String selectedBancosFuncionarios;

	public void setDao(br.com.splgenerator.dao.ModRhDao dao) { this.dao = dao; }
	public void setLog(br.com.splgenerator.audit.ILog log) { this.log = log; }

	public HtmlDataTable getHtmlDataTable() { return htmlDataTable; }
	public void setHtmlDataTable(HtmlDataTable htmlDataTable) { this.htmlDataTable = htmlDataTable; }

	public Date getDataAdmissaoDe() { return dataAdmissaoDe; }
	public void setDataAdmissaoDe(Date dataAdmissaoDe) { this.dataAdmissaoDe = dataAdmissaoDe; }

	public Date getDataAdmissaoAte() { return dataAdmissaoAte; }
	public void setDataAdmissaoAte(Date dataAdmissaoAte) { this.dataAdmissaoAte = dataAdmissaoAte; }

	public java.util.List<br.com.splgenerator.model.cadastro.Funcionario> getFuncionarios() { return this.funcionarios; }

	public int getMesAniversario() { return mesAniversario; }
	public void setMesAniversario(int mesAniversario) { this.mesAniversario = mesAniversario; }

	public String getSelectedBancosFuncionarios() { return selectedBancosFuncionarios; }
	public void setSelectedBancosFuncionarios(String selectedBancosFuncionarios) { this.selectedBancosFuncionarios = selectedBancosFuncionarios; }

	public String buscarAniversariantes() {
		log.log("INFO", "Buscando Aniversariantes do mes: " + this.mesAniversario);
		this.funcionarios = dao.getFuncionariosAniversariantes(this.mesAniversario);
		return "relatorioAniversariantes";
	}

}
