// =======================================================================================
// Warning. Do not edit this file directly.  This file was built with the SPL generator.
// Eduardo Andrade - <%= Time.now %>
// =======================================================================================
package br.com.splgenerator.web.cadastro;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.component.html.HtmlDataTable;
import javax.faces.context.FacesContext;

import br.com.splgenerator.audit.ILog;
import br.com.splgenerator.dao.ModRhDao;
import br.com.splgenerator.model.cadastro.Funcionario;
import br.com.splgenerator.monitoring.ModRhStats;

@ManagedBean
@SessionScoped
public class GerenciarFuncionario implements Serializable {

	private static final long serialVersionUID = 1L;

	@ManagedProperty(value = "#{$VP-DAO}")
	private ModRhDao dao;
	@ManagedProperty(value = "#{$VP-AUDIT}")
	private ILog log;

	private transient HtmlDataTable htmlDataTable;

	private br.com.splgenerator.model.cadastro.Funcionario _novoFuncionario;
	private br.com.splgenerator.model.cadastro.Funcionario _editarFuncionario;

	public GerenciarFuncionario() {
		_novoFuncionario = new br.com.splgenerator.model.cadastro.Funcionario();
		_editarFuncionario = null;
	}

	public void setDao(ModRhDao dao) { this.dao = dao; }
	public void setLog(ILog log) { this.log = log; }

	public HtmlDataTable getHtmlDataTable() { return htmlDataTable; }
	public void setHtmlDataTable(HtmlDataTable htmlDataTable) { this.htmlDataTable = htmlDataTable; }

	public java.util.List<br.com.splgenerator.model.cadastro.Funcionario> getFuncionarios() {
		log.log("TRACE", "Executando getFuncionarios()...");
		ModRhStats.incrementCounterSelectFuncionarios();
		return dao.getFuncionarios();
	}

	public String atualizarFuncionario() {
		log.log("TRACE", "Executando atualizarFuncionario()...");
		ModRhStats.incrementCounterUpdateFuncionarios();
		dao.atualizarFuncionario(_editarFuncionario);
		addFacesMessage("Funcionario editado com sucesso!");
		return "gerenciarFuncionarios";
	}

	public String salvarFuncionario() {
		log.log("TRACE", "Executando salvarFuncionario()...");
		ModRhStats.incrementCounterInsertFuncionarios();
		dao.salvarFuncionario(_novoFuncionario);
		addFacesMessage("Funcionario adicionado com sucesso!");
		this._novoFuncionario = new br.com.splgenerator.model.cadastro.Funcionario();
		return "gerenciarFuncionarios";

	}

	public String removerFuncionario() {
		log.log("TRACE", "Executando removerFuncionario()...");
		ModRhStats.incrementCounterDeleteFuncionarios();
		dao.removerFuncionario((Funcionario) htmlDataTable.getRowData());
		addFacesMessage("Funcionario removido com sucesso!");
		return null;

	}

	public String selecionarFuncionario() {
		log.log("TRACE", "Executando selecionarFuncionario()...");
		this._editarFuncionario = (Funcionario) htmlDataTable.getRowData();
		return "editarFuncionario";

	}

	public Funcionario getNovofuncionario() { return _novoFuncionario; }
	public void setNovofuncionario(Funcionario value) { _novoFuncionario = value; }

	public Funcionario getEditarfuncionario() { return _editarFuncionario; }
	public void setEditarfuncionario(Funcionario value) { _editarFuncionario = value; }

	private void addFacesMessage(String message) {
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(message));
	}

}
